### ISSUE TITLE
Increase "Prevent echo feedback" duration threshold

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#148]

**Comment by noah1234j** [comment]
Hi there, this feature does not appear to work correctly with my midi controller. My motorized faders still try to take controll while I'm sliding them. Is that what this bug is? Also please let me know if there is anything I can do to help you troubleshoot/fix this. Thanks for all your work on this project, it is incredible!!!

**Comment by noah1234j** [comment]
Also if there is any workaround, I would love to hear it. Driving me crazy right now

**Comment by helgoboss** [comment]
Yes, it's that. But as noted in the forum, "Prevent echo feedback" checkbox only has an effect within one mapping, not across multiple mappings. As soon as this is fixed, you will be good to go *in case* you have only one feedback-enabled mapping pointing to one fader. If you have multiple feedback-enabled mappingss pointing to one fader, let me know.

No workaround I know of except switching off feedback for that mapping.

**Comment by noah1234j** [comment]
Thanks so much. Right now I have only one feedback enabled mapping per fader. Also, love the work you've done with this, sent you a donation to help support the project. Please let me know if there is anything else I can do to help.

**Comment by helgoboss** [comment]
@noah1234j Does it work for you now (with 2.2.0)?
