### ISSUE TITLE
Allow rapid controller capture

### ISSUE THREAD

**Issue by stereokai** [helgoboss/realearn#158]
With the "Learn Many" feature, it would be amazing to be able to capture as many controls uninterrupted.

That means - not requiring the user to choose a target for each source captured - only creating the mappings and allowing the user to continue with no additional input (confirmation boxes, input fields, etc.)

For example, it will make it straightforward to lay out an entire controller in ReaLearn, control by control, and not having to think what I want to map each control to, or plan that in advance.

**Comment by helgoboss** [comment]
> For example, it will make it straightforward to lay out an entire controller in ReaLearn, control by control, and not having to think what I want to map each control to, or plan that in advance.

This is already how it works. In order to lay out an entire controller, you should use the "Controller mappings" compartment. If you click "Learn many" there, it will rapidly learn just the controls, not prompt for targets. I recommend to take a look in the user guide, section "Controller mappings".

**Comment by stereokai** [comment]
I see! I was not aware of that. Thanks you for this explanation :)
