### ISSUE TITLE
Add instance track and possibility to change it (e.g. for track pinning)

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#161]
Candidates:

- Track
- MIDI source channel

Maybe one could even define a default mapping per group/instance (should be looked at in combination with #159!) which acts as potential inheritance source for mappings. That could be really useful for using ReaLearn to specific values of multiple targets (and hence multiple mappings) on the press of a one button - which would be represented by the mapping source in the group default mapping.

**Comment by helgoboss** [comment]
One other user request that is relevant in this context: 

> Bei Controller-Mappings sollte es zwei virtuelle Generalschalter geben (die man dann per Mapping mit seinem Hardware-Controller an/ausschalten kann):

> Schalter 1 "Make relative":
Alle absoluten sources (Fader oder Potentiometer) in relativ umwandeln (mit den bekannten Vor- und Nachteilen, bei größeren Änderungen bzw. wenn man schon an einem Ende des Regelbereichs ist, deswegen schaltbar)

> Schalter 2 "Fine":
Für alle relativen targets (auch die aus Schalter 1, und "incremental buttons") temporär die Auflösung verfeinern (Faktor 10 oder 20)

**Comment by helgoboss** [comment]
Forcibly overriding certain mapping settings even they don't have any inheritance defined could be an alternative (or additional?) way to approach this. Typical "override" use cases are #203 and #204.

**Comment by vonglan** [comment]
Idea for this: Meta Mapping.

Allow the user to define one "Meta Mapping" for each Group (in each ReaLearn instance), that allows general, run-time modification of all mappings in that group.
This Meta Mapping would offer a subset of the fields of a normal mapping.
But each with a checkbox "active" beside it, that gets set by ReaLearn as soon as the user enters something into the field.
Rea Learn needs to evaluate the Meta Modifying mapping each time that a mapping of that group is processed. 

For all interesting use cases, the fields then need to contain dynamic content (EEL formula) that modifies the values in the normal mapping, e.g. Encoder Speed: multiply with Parameter x. (See #204 ).
(I suppose this is easy for numeric fields, but complicated or impossible for others - maybe can be achieved when the power user looks at the JSON representation?)
The ? : notation in EEL would also allow "Replace IF": If Parameter x is set, override the current value with y, otherwise leave it as it is.
`y = P1 > 0 ? 0.5 : x`

**Comment by helgoboss** [comment]
Sounds good, will think about that.

**Comment by vonglan** [comment]
Looking at it again, I think it might be easier to implement #203 and #204 in a specific (dynamic possibilities for just these two fields) rather than a generic way.

**Comment by helgoboss** [comment]
Maybe. I'm sure there are some cases where I should deviate from my usual strategy to implement everything in a highly generic manner. Maybe this is one of them. Let's see.

**Comment by helgoboss** [comment]
"Default mapping" and "Mapping to inherit stuff from" should probably be 2 different things. Making both the same doesn't make sense. Because if you want to inherit stuff, you have less need for a default mapping. Both are mechanisms for being quicker but "default mapping" achieves this by duplication and "inheritance" achieves this by avoiding redundance. Two different things.
