### ISSUE TITLE
Add "<This>" FX selector

### ISSUE THREAD

**Issue by jackmau** [helgoboss/realearn#186]
I very much appreciate the fact that realearn is enough smart to suggest you to relativise its assignments when saving a preset...but I found myself unable to use it as it does also apply to assignments which have the very same realearn instance as a target (typically to modify realearn internal parameters for paging/shifting behaviour). In my opinion it shouldn't change those, maybe identifying them as in #159 . An easy workaround is to have two separate realearn session, one that manages realearn parameters and another for the focused plugin, but that will force the user to lose a part of the benefit of controller projection.

Forgot to add I am on latest Realearn 2.4 and reaper 5.99

**Comment by helgoboss** [comment]
Yes, this workflow enhancement is at the moment pretty much tailored to the "Auto-load preset: Depending on focused FX" use case.

Good point. It should detect that it itself is the target and be able to find itself even if it's at another position or has another ID or name (which it wouldn't at the moment).

**Comment by jackmau** [comment]
> Yes, this workflow enhancement is at the moment pretty much tailored to the "Auto-load preset: Depending on focused FX" use case.

Of course and indeed, I have been experiencing the issue exactly while trying this mode. 

> Good point. It should detect that it itself is the target and be able to find itself even if it's at another position or has another ID or name (which it wouldn't at the moment).

Sounds even smarter than I originally envisioned

**Comment by helgoboss** [comment]
> > Yes, this workflow enhancement is at the moment pretty much tailored to the "Auto-load preset: Depending on focused FX" use case.
> 
> Of course and indeed, I have been experiencing the issue exactly while trying this mode.

Okay, sounds like your use case is to employ conditional activation in a preset that's auto-loaded. Is that correct? If yes, I will rename this issue accordingly.

**Comment by jackmau** [comment]
yes @helgoboss, I was trying to be original with the issue name, but that makes more sense

**Comment by helgoboss** [comment]
This could also need #241

**Comment by helgoboss** [comment]
Summary so far: The todo in this ticket is to somehow make it possible to refer to *this* ReaLearn instance - no matter where it is. Because that's the precondition for conditional activation to be used in universally reusable presets. Ideas how to achieve that:

1. Provide a `<This>` FX selector which automatically refers to this ReaLearn instance (sounds nice because it's analog to the track selector `<This>`).
2. Maybe in addition provide a dedicated target for controlling the parameters of this ReaLearn instance (but I consider this as a nice-to-have convenience feature on top of this).
