### ISSUE TITLE
Best Practice for using VST-specific mapping sets

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#230]
Split from #226 .
I would like to create multiple sets of VST-specific mappings (that use virtual parameters from multiple Controller Mappings as source, see #205 ), and then use them again and again in different projects, and possibly share them with other users. For example:
- Mapping for Diva
- Mapping for Hive
- Mapping for Colour Copy

It is not clear to me what is the best way to do this.

One idea is to save the ReaLearn instance with the Mapping along with the respective VST as an FX Chain.
But what is the correct configuration for Target / FX in all of the Mappings? 
I want to control the VST even when it is not focused, so „focused“ does not seem right. Identifying it be position in FX Chain is also not practical: when I add a MIDI FX script before the VST, for example, the position will change. Good would be to address it by name pattern (as you commented in #226 ).

It is also not clear to me what is Best Practice if I want to flexibly combine such a VST instrument mapping with a separate mapping for an effect VST (like Colour Copy). Is there a possibility to store these separately, and load them together in the "Main Mapping" compartment of an instance? Or is the current preset always replaced when I load a different one?

**Comment by vonglan** [comment]
Just noticed that this overlaps with some of the requirements in #227 , and also the ideas outlined in #109 .
But I am still lacking a complete picture. Maybe because I did not yet experiment with multiple VSTs, multiple instances etc.

**Comment by vonglan** [comment]
> It is also not clear to me what is Best Practice if I want to flexibly combine such a VST instrument mapping with a separate mapping for an effect VST (like Colour Copy). Is there a possibility to store these separately, and load them together in the "Main Mapping" compartment of an instance? Or is the current preset always replaced when I load a different one?

--> It seems the solution for this is to have two separate ReaLearn instances in the track. One for the instrument VST, one for the effect VST.

**Comment by helgoboss** [comment]
> Split from #226 .
> I would like to create multiple sets of VST-specific mappings (that use virtual parameters from multiple Controller Mappings as source, see #205 ), and then use them again and again in different projects, and possibly share them with other users. For example:
> 
> * Mapping for Diva
> * Mapping for Hive
> * Mapping for Colour Copy
> 
> It is not clear to me what is the best way to do this.
> 
> One idea is to save the ReaLearn instance with the Mapping along with the respective VST as an FX Chain.

Yeah, I think there are many options but which one is the best for your use case and whether there's an important feature for that still missing, it's not clear yet. Let's find out.

> But what is the correct configuration for Target / FX in all of the Mappings?
> I want to control the VST even when it is not focused, so „focused“ does not seem right. Identifying it be position in FX Chain is also not practical: when I add a MIDI FX script before the VST, for example, the position will change. Good would be to address it by name pattern (as you commented in #226 ).

Addressing the FX by name is already possible by using the "By name" selector. This would be one option. However, this is not the best solution in your case. You want to build a preset that is universally usable, right? One that also works with "Auto-load preset" but also without ... funny, because I created an issue for that just today :) It's #228. The answer to this? Not clear yet, let's think about it and see what we come up with. But I'd suggest to continue this part of the discussion in #228, not here.

> 
> It is also not clear to me what is Best Practice if I want to flexibly combine such a VST instrument mapping with a separate mapping for an effect VST (like Colour Copy). Is there a possibility to store these separately, and load them together in the "Main Mapping" compartment of an instance? Or is the current preset always replaced when I load a different one?

They are always completely replaced. This is by design as explained in #209. Exactly, multiple instances are the intended way of doing this and my intention is to continue improving that way instead of adding more and more "combination-related" functionality for usage within a single instance. I want to account for the fact that ReaLearn is not a global REAPER extension but a VSTi - which in itself provides many advantages, such as multiple instantiation.

> Just noticed that this overlaps with some of the requirements in #227 , and also the ideas outlined in #109 .
> But I am still lacking a complete picture. Maybe because I did not yet experiment with multiple VSTs, multiple instances etc.

The truth is, there's no complete picture yet. We are painting it right now. ReaLearn is usable for many things already but users come up with new things that I didn't anticipate. Or things that I slightly had in mind but that I couldn't yet drive to perfection. What you want to do, the reusable preset thing, I think it's great! Let's think about it together and find out what's the best possible way to approach this.

Do you think this issue could be closed in favor of continuing the discussion in the aforementioned, more focused issues?

**Comment by vonglan** [comment]
> Addressing the FX by name is already possible by using the "By name" selector. This would be one option. However, this is not the best solution in your case. You want to build a preset that is universally usable, right? One that also works with "Auto-load preset" but also without ... funny, because I created an issue for that just today :) It's #228. The answer to this? Not clear yet, let's think about it and see what we come up with. But I'd suggest to continue this part of the discussion in #228, not here.

I am not sure whether I need "auto-load preset". I certainly want to be able to control a VST when it is NOT in focus - I do not understand yet how these features work.

> Do you think this issue could be closed in favor of continuing the discussion in the aforementioned, more focused issues?

Yes, of course.
