### ISSUE TITLE
Virtual targets/sources identified by names instead of numbers

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#244]
If we have standardized virtual source/target sets like "analog synth" (#205 ), that are shared by many users, we might get "number range conflicts" in the 100 multis.
To avoid this, they could be identified by names in the UI and JSON (maybe with a namespace convention, like "AS/Filter Cutoff", or "FX/Rate"), and internally be represented by hash values of those names.

Two other aspects:
The current numbers do not really offer anything (beside being a default name, if you do not give a name), no-one would miss them if they were removed.
For the "analong synth" virtual sources/targets set, I see something like 75 multis already. So we could run out of the currently 100 available multis.

**Comment by helgoboss** [comment]
> If we have standardized virtual source/target sets like "analog synth" (#205 ), that are shared by many users, we might get "number range conflicts" in the 100 multis.
> To avoid this, they could be identified by names in the UI and JSON (maybe with a namespace convention, like "AS/Filter Cutoff", or "FX/Rate"), and internally be represented by hash values of those names.

This makes a lot of sense and shouldn't be that much work. Putting this on the high prio list.

> Two other aspects:
> The current numbers do not really offer anything (beside being a default name, if you do not give a name), no-one would miss them if they were removed.

I chose Multi/Button + numbers because this is a popular convention with many small controllers. Quoting from the user guide:

> Just imagine the "8 generic knobs + 8 generic buttons" layout which is typical for lots of popular controllers. You can easily model that by assigning 8 multis and 8 buttons.

I think having "increasing numbers" are the best default for virtual sources/targets. In your specific domain you can establish and follow your own conventions for naming virtual sources/targets, however, in a very generic domain it's actually hard to come up with something that makes sense and is reusable. Numbers are simple, reusable and make at least a little bit sense. They are the easiest and most straightforward way to effectively distinguish different controls.

Also, I will need to support existing presets. So I guess I will add a new option "<Name>" and provide a text field where you can enter the name.

> For the "analong synth" virtual sources/targets set, I see something like 75 multis already. So we could run out of the currently 100 available multis.

Makes sense.

**Comment by helgoboss** [comment]
Implemented in upcoming 2.8.0-pre4.

No special characters, no whitespace, limited to 16 characters.
