### ISSUE TITLE
Step Size not available in Controller Mapping

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#268]
Source is an NRPN which is physically a button but sends 0 to 2.
I would like to configure that as incremental button with step size 10%.
Virtual Target is of type Multi.
I would expect the Mappping window to offer "Step Size", but "Speed" is displayed (and it does not work as expected for step size).

**Comment by helgoboss** [comment]
"Step size" is not available because it doesn't make logical sense at this point in the processing chain. You need to define that in the main mapping (= the mapping, which actually knows its target).

**Explanation:** ReaLearn's sources can emit exactly 2 types of messages: Absolute ones (e.g. "Set to 20% of its full range!") and relative ones (e.g. "3 increments up please!"). That's all there is and all it needs. There's no "Please increment the target value by 3%". That's because at source level it's too early to decide about a step size. It depends totally on the target which step sizes are reasonable and which not. When you have a controller mapping with a virtual target, the target is not known (I think we have talked about this already, I vaguely remember). Targets sometimes even enforce specific minimum step sizes. All you can do on the level of virtual controller mappings is say "Hey, don't just emit 1 increment when the button is pressed but 3 increments!" That's what the "Speed" setting does. Also explained in the user guide.

**Comment by helgoboss** [comment]
Ah, something that might not be obvious: The main mapping "Step size Max" needs to be set to a higher value than "Step size Min" if you want the "Speed" setting in the virtual mapping to have an effect!

The "Step size Max" setting (in case you have wondered what it is for) is to control how much the step size is allowed to increase by acceleration. Explained in the manual. Now think about it this way: The "Speed" setting of the virtual mapping is just like simulating "Acceleration". If you don't allow the main mapping to respond to acceleration, then it won't have any effect at all.

**Comment by vonglan** [comment]
Thanks for your explanation.
It works for my use case (Virtual Targets/Sources to decouple Controller from VST) when I use Speed Min=Max=10x in the Controller Mapping, and then Step Size min=1% and max=10% in the Main Mapping.
I can also swap the Controller for an Encoder without adapting the Main Mapping, so it is properly decoupled.
Only problem is #269 .

Two comments:
> Ah, something that might not be obvious: The main mapping "Step size Max" needs to be set to a higher value than "Step size Min" if you want the "Speed" setting in the virtual mapping to have an effect!

I found that it also works if I set them both to the same value. And it does not do any harm to the minimum step size achievable with an "absolute" knob.

> The "Step size Max" setting (in case you have wondered what it is for) is to control how much the step size is allowed to increase by acceleration. Explained in the manual. 

You could ADD the following words in the manual:
`Step size Max is used to limit the effect of encoder acceleration (in case of rotary encoders which support this, 
ADD: or buttons in incremental mode)
`

`Speed Min/Max: When you choose a discrete target 
ADD: (all virtual targets are discrete)
`

**Comment by helgoboss** [comment]
Okay, making some additions.
