### ISSUE TITLE
Target "ReaLearn: Navigate within group" (Action/Target Lists)

### ISSUE THREAD

**Issue by Poofox** [helgoboss/realearn#325]
Allow creating lists of actions or targets to be cycled through or triggered at random.  Cycling should be either forward or backward.  Should support lists by name, number, ID etc.

Example (one encoder cycles selection through 3 non-consecutive tracks):
Select only track 1
Select only "Synth"
Select only "Synth 2"

Example (one momentary button triggers a random region from a list of regions):
Play region 1 after current region
Play region 2 after current region
Play region 32 after current region
Play region 73 after current region

**Comment by helgoboss** [comment]
As you've figured out in the forum, this is now partially implemented via #391 (target value sequences). However, in order to support all the little features you mention, there's still work necessary.

> Allow creating lists of actions or targets to be cycled through or triggered at random.

You can create lists of concrete target values for one target now and cycle through them. Cycling through different targets is not and will not be in scope of the target value sequence feature. That would probably be much better as a new "Group interaction".

Also, random cycling is not supported right now. That could be an easy addition.

> Cycling should be either forward or backward.  Should support lists by name, number, ID etc.

Backward cycling is supported by checking "Reverse".

"By name" is not supported. That could be a possible addition in combination with the "Project: Navigate within tracks" target, probably not that difficult to do.

"By number" is possible for all continuous targets. You can enter percentages or use the target's native unit. I haven't tried yet but discrete targets such as "Project: Navigate with within tracks" might suffer the known issue that entered values can get out of date if you add/remove tracks (because ReaLearn thinks in percentages). If yes, this will be solved in a clean and general way by "Discrete processing" (don't remember the issue number).

> Example (one encoder cycles selection through 3 non-consecutive tracks):
> Select only track 1
> Select only "Synth"
> Select only "Synth 2"

Without names, this is possible right now. With names it should be possible once entering track names are supported. Note to self: Could be distinguished from numbers by using quotes.

> Example (one momentary button triggers a random region from a list of regions):
> Play region 1 after current region
> Play region 2 after current region
> Play region 32 after current region
> Play region 73 after current region

Cycling via momentary button is possible now (incremental buttons mode). However, to cycle between regions, ReaLearn would need a "Project: Navigate within markers/regions" target, which it doesn't have yet. If you need it, FR please.

**Comment by Poofox** [comment]
Thank you very much for the reply, clarfication and feature!

________________________________

**Comment by helgoboss** [comment]
Note to self: Implement this as a generic target: "ReaLearn: Navigate within group" (or "Cycle group").
