### ISSUE TITLE
Toggle feedback transformation not working

### ISSUE THREAD

**Issue by cjunekim** [helgoboss/realearn#36]
I am using realearn to change the preset of an FX with a midi button. What I want is I press the button and the FX goes to preset #20 and then press it again it goes to preset #0(factory reset).

It works with my midi button working as momentary. However, the feedback doesn't work properly. I guessed it was because the feedback was sent as value 20, not 127, which is expected from the midi controller.

So I decided to use the feedback transformation: x = (y>1) ?1 : 0

But the feedback doesn't work. Changing the value with the Value slider of Target on the Mapping window works properly with feedback though.

**Comment by cjunekim** [comment]
Update. I figured that this is not about feedback transformation. It's about Track FX preset.

When the target is a track mute button, the feedback works expectedly. But when the target is Track FX preset, it behaves strangely.

I have investigated inside via a virtual MIDI cable. When I press a midi button, the feedback comes out only when the preset become #20, not coming back to preset #0. However, with a track mute button as the target, the feedback comes out in both times. All the Mode Type is toggle.

**Comment by cjunekim** [comment]
Update2. I learned more about this issue.

There is also some issue with feedback transformation as well.

Pick a midi button(momentary) and make it as a source, and add reacomp and set its Lowpass to the target. The Mode could be Absolute for example.

When Target's Min is at 0% and Max is any number between 0% to 50%, and the feedback transformation string is set to y=1-x, the result is very strange. The feedback output is always 127. Always, whether you press or release the button. However, when you set the transformation string to y=x, it works as expected.

**Comment by helgoboss** [comment]
I'll try this source/target combination. However, there's something wrong with your feedback transformation formulas:

    x = (y>1) ?1 : 0

Neither x nor y should ever be greater than 1. It's supposed to be always between 0 and 1. So with your formula you will always end up with 0. Which means "Source Min" will be sent to your controller, no matter what's the actual target value.

    y=1-x

This doesn't do anything. In feedback transformation formulas you need to assign a value to x, not y (because x represents the resulting normalized feedback value and y the current normalized target value). Best have a look in the user guide, it's explained there.

Concerning logging MIDI feedback, you don't have to deal with virtual MIDI cables. Just choose "FX output" as MIDI output and slap a Cockos ReaControlMIDI below it (which lets you show the log).

**Comment by cjunekim** [comment]
Yeah. At first, I misunderstood the range of x and y. But my second and third ones are written after that correction of understanding.

`y=1-x` was my typo when writing the comment. It actually was x=1-y. Could you confirm this?

When the target max was set at 50% or lower, the feedback behaves strangely.

All I found was, to correct the misbehavior, I had to modify my formula. In order to acheive the feedback reversed, I had to do,

`x=1-y-1+TM
`
here, TM stands for Target Max in the form of 0..1.

**Comment by cjunekim** [comment]
Any updates on this issue?

**Comment by helgoboss** [comment]
Looking into it right now. Understood the issue.

**Comment by helgoboss** [comment]
This was indeed a bug. The processing order was inconsistent. The bug is fixed in upcoming v1.12.0-pre8.

The control processing order is:

1. Apply source interval
2. Apply transformation
3. Apply target interval
4. Apply reverse
5. Apply rounding

The old feedback processing order was:

1. Apply reverse
2. Apply transformation
3. Apply target interval
4. Apply source interval

The new feedback processing order is:

1. Apply reverse
2. Apply target interval
3. Apply transformation
4. Apply source interval

Latter order is consistent with control processing order (exactly the reverse) and makes the transformation fomula work on the complete unit interval (`0..1`).

Please note that this will change the behavior of existing feedback transformation formulas if used in combination with source or target interval restrictions, so they might need some adjustment. Sorry for any inconvenience.

@cjunekim Good catch!
