### ISSUE TITLE
Go to regions : option to seek after a given number of bars instead of full region

### ISSUE THREAD

**Issue by dissofiddle** [helgoboss/realearn#377]
Hello, 
In reaper seeking preferences, you can set reaper so that it  waits  a given number of bars or after a full region before seeking.
Would it be possible to give the same option in Realearn (and not only full region)  ?

**Comment by helgoboss** [comment]
ReaLearn just uses the global preferences. If you set "Play to end of n more measures before", it will do the smooth seek after n measures.

If you want to set a different value per mapping, that's not possible because AFAIK the REAPER API doesn't provide a way to customize the smooth seek waiting time for one particular smooth seek operation.

Feel free to reopen if you meant something else or have an idea.
