### ISSUE TITLE
Feedback for "Toggle-only button" not working reliably when changing from controller

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#399]
Target is ReaComp, Param 16 AutoMkUp

Release 2.9.1

When I press the OB6's toggle button, the feedback for the target parameter is not reliably updated. Sometimes it works correctly (several times in succession), sometimes it behaves erratically (see example below). 
The other way always works: when I change the parameter in ReaComp GUI, the LED lights correctly on the OB6.

press --> parameter on, light off
press --> parameter off, light on
press --> parameter on, light off
press --> parameter off, light on
press --> parameter on, light on (!!!)
press --> parameter off, light on
press --> parameter on, light off
press --> parameter off, light on

Controller Mapping:
{
  "mapping": {
    "id": "333399f6-b6ae-41cc-9c3e-8159c183147f",
    "name": "Oscillator Keyboard Tracking",
    "source": {
      "type": 6,
      "channel": 0,
      "number": 11,
      "character": 5,
      "isRegistered": false,
      "is14Bit": true,
      "oscArgIndex": 0
    },
    "mode": {
      "maxSourceValue": 0.00006103888176768602
    },
    "target": {
      "category": "virtual",
      "fxAnchor": "id",
      "controlElementType": "button",
      "controlElementIndex": "SY/OscKeyTrack",
      "useProject": true,
      "moveView": true,
      "seekPlay": true
    }
  }
}
Main Mapping:
{
  "mapping": {
    "id": "71617141-c0f3-42db-ab98-289ce78a5cbd",
    "name": "14",
    "source": {
      "category": "virtual",
      "isRegistered": false,
      "is14Bit": false,
      "oscArgIndex": 0,
      "controlElementType": "button",
      "controlElementIndex": "SY/OscKeyTrack"
    },
    "mode": {
      "type": 2
    },
    "target": {
      "fxAnchor": "id",
      "fxIndex": 2,
      "fxGUID": "F7D15AFC-B3E5-9240-B7B3-939107507D3C",
      "paramIndex": 15,
      "useProject": true,
      "moveView": true,
      "seekPlay": true,
      "oscArgIndex": 0
    }
  }
}

**Comment by helgoboss** [comment]
Thanks. It would be very helpful if you could attach a demo project which reproduces this (by routing MIDI items to ReaLearn, so that I just have to play the project and see what's happening).

**Comment by vonglan** [comment]
example project attached
[issue399 toggle-only feedback.RPP.zip](https://github.com/helgoboss/realearn/files/6834692/issue399.toggle-only.feedback.RPP.zip)

**Comment by vonglan** [comment]
Not sure whether this has anything to do with the issues, but I get two console warnings frequently:

`ReaLearn warning: The preset that is about to load was saved with a newer version of ReaLearn. Things might not work as expected. Even more importantly: Saving the preset might result in loss of the data that was saved with the new ReaLearn version! Please consider upgrading your ReaLearn installation to the latest version.`

`ReaLearn warning: Invalid command ID 0`

I haven't looked very much whether the first one is always justified. Certainly it was sometimes.

**Comment by helgoboss** [comment]
Mmh, several things:

- You should definitely get rid of the first warning! This can potentially affect a lot. It probably occurs because you have used a 2.10 pre and saved one of your presets or projects with it. So you either need to upgrade ReaLearn or - if you are fine with losing any 2.10 changes - resave the project and affected presets (you will find the ReaLearn version used to save the preset in the corresponding JSON file).
- The second warning indicates that some of your "Project: Invoke REAPER action" targets contain `"commandName": "0"` in the JSON. Did you edit the JSON directly? I think it's not possible to do this via UI because you only get to pick a valid action. Anyway, you can fix it in your preset JSON files by removing this line and fix it in your project by resaving the project.
- In your example project, you use mode "Normal". What you really want is "Toggle buttons", right? Otherwise pressing your hardware button will not do anything if the target is already at 100%. This is also what I observed when playing the project: It was just working the first time, then the target got stuck at 100%. Because "Toggle-only button (avoid!)" (what you use) will only ever send "on", never "off". Is this maybe the solution to your problem already? If the target value isn't changed, ReaLearn will not send feedback.
- By the way, in the latest ReaLearn prereleases you can log incoming and outgoing messages, which might help you to debug the issue yourself. In your case it outputs something like this (I excluded the consumed messages):

    ```
    635846.659 | ReaLearn DYoBvn9M | Control input    | {"channel":0,"number":11,"value":1,"is_registered":false,"is_14_bit":true} (matched)
    635846.665 | ReaLearn DYoBvn9M | Control input    | {"channel":0,"msb_controller_number":6,"value":1} (unmatched)
    635847.399 | ReaLearn DYoBvn9M | Control input    | {"channel":0,"number":11,"value":0,"is_registered":false,"is_14_bit":true} (matched)
    635847.404 | ReaLearn DYoBvn9M | Control input    | {"channel":0,"msb_controller_number":6,"value":0} (unmatched)
    ```

**Comment by vonglan** [comment]
Thanks for the help.

About the "newer release warning":
Release 2.10 only appeared in my example preset for issue 396 (and that was practically empty when I opened it). I deleted it. The warning did not appear again.
But I think "The preset that is about to load" might be incorrect, because the message came up a lot of times, without me loading that preset.

About CommandName:0:
No, I do not have any „commandName:0“ in my presets.
```
edo@MBP21 presets % grep commandName */*
main/playtime-x3.json:        "commandName": "RSdb4615229f6a881d401425e10c6a623bede69e88",
main/playtime-x3.json:        "commandName": "RSdb4615229f6a881d401425e10c6a623bede69e88",
main/playtime-x3.json:        "commandName": "RSdb4615229f6a881d401425e10c6a623bede69e88",
main/playtime-x3.json:        "commandName": "RSdb4615229f6a881d401425e10c6a623bede69e88",
grep: temporär weggestellt/controller: Is a directory
grep: temporär weggestellt/main: Is a directory
edo@MBP21 presets %
```

--> Anyway, I will see whether that message appears again. Maybe it was somehow tied in with the "newer release warning".

About toggle mode in the example project:
Yes, for the example project switching the Mode to „Toggle button“ in Tuning fixes it.
That does not explain the original symptom that I observed.
However, I also saw that I had the same mapping problem in that place, and after fixing that, it works fine.
(right before that, I saw a consistent 2-1 pattern - not the same pattern that I observed when I opened this ticket.)

Thanks for the hint with the debug messages. However, as I do not spend much time with ReaLearn at the moment, I would like to stick to the main release for a while.

**Comment by vonglan** [comment]
> Yes, for the example project switching the Mode to „Toggle button“ in Tuning fixes it.

Thought about it again. I required the "Toggle-Only Button" only for special cases (where I want to iterate through a range of target values).
The problem here can also be solved by using 
- Source character = Range
- Tuning = Standard
