### ISSUE TITLE
<Selected> track only works on first track when using multiple selection

### ISSUE THREAD

**Issue by DLongoni** [helgoboss/realearn#4]
When multiple tracks are selected and target it set to some action to be performed on <Selected> Track, then the action is only performed on the first track of the multiple selection, which is unexpected I guess

**Comment by X-Raym** [comment]
+1 for this,
Track Parent, or multi mapping aren't good workarround cause it is not flexible compared to just track selection.

Thx!

**Comment by helgoboss** [comment]
Note to self: Probably the best way to implement this internally would be to generalize the target resolve step to support resolving to multiple targets internally instead of just one. That way a separate treatment of each selected track could be achieved which is important for relative control. Plus, it opens ReaLearn up for more interesting multi-control use cases at the same time.

**Comment by helgoboss** [comment]
In upcoming RC, a new selector `<All selected>` is available which lets all \"Track: ...\" targets operate on all selected tracks. FX and sends target work only on the first track, even if `<All selected>` is chosen.
