### ISSUE TITLE
Target "Adjust Track FX Parameter"

### ISSUE THREAD

**Issue by DLongoni** [helgoboss/realearn#42]
It would be nice to have a target that behaves like the "Adjust Track FX parameter x" action. The action works just fine, but there is no feedbackIf I map it to a certain Knob I can use it properly to work on the track parameter, but when I select that channel the next time my knob will be set to 0 and I will have the usual unwanted parameter jump, etc etc.

A workaround for this is to handpick all the params I need for each track and map them using a "Track FX Parameter" target, which works perfectly (with the "track must be selected" flag on). The problem is that if I have many tracks with many effects I will need 1 mapping per knob per effect, while with the Adjust Track FX" param I only have as many mappings as the knobs, and for each channel I need just to add a certain parameter to Track FX Parameters. 

Cheers!

**Comment by helgoboss** [comment]
`CountTCPFXParms` and `GetTCPFXParm`

**Comment by helgoboss** [comment]
This is possible in upcoming pre-release.

Example for controlling the first FX parameter displayed in the track control panel:

1. Set FX to `<Dynamic>` and enter `tcp_fx_indexes[0]`
2. Set FX parameter to `<Dynamic>` and enter `tcp_fx_parameter_indexes[0]`

Unfortunately this is not too useful because it seems REAPER doesn't allow one to change the order of the TCP parameters.
