### ISSUE TITLE
Support track grouping parameters

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#45]
From ChocolateHawkins:

> Another issue I've noticed with Realearn is when I map to a VCA master fader, the VCA follow functions (fader, solo, mute, etc.) do not work.

**Comment by helgoboss** [comment]
I think this needs to be implemented manually by evaluating `GetSetTrackGroupMembership`. Could be easier to do when implementing #4 by providing the foundation to allow resolving to multiple targets at once.

**Comment by helgoboss** [comment]
It works for record arm already, maybe for some other things as well?

**Comment by TheMiscreant** [comment]
> From ChocolateHawkins:
> 
> > Another issue I've noticed with Realearn is when I map to a VCA master fader, the VCA follow functions (fader, solo, mute, etc.) do not work.

To add a detail: it'd be nice to bypass grouping by holding down 'SHIFT' when toggling a parameter via ReaLearn.

**Comment by nofishonfriday** [comment]
I'm not the requester (obviously) but just a thought: In REAPER VCA masters (new terminology: Leaders) don't move VCA slave (Followers) faders by design (there's Volume Lead/Follow for that), same with solo, mute.

The other track grouping functions (volume, solo, mute Lead/Follow) should also be handled by REAPER automatically when controlling a Lead track I think, at least they do here when controlled via Reaper's native MIDI learn or control surface.

So I'm not sure if this needs handling on ReaLearn side, but maybe I'm misunderstanding. :)

**Comment by helgoboss** [comment]
I renamed this to "Support track grouping parameters" because VCA works already!

**Comment by helgoboss** [comment]
I added a "Respect track grouping" and "Selection ganging" checkbox to all relevant targets.

One limitation: Volume, pan and width targets can respect track grouping **only** if selection ganging is also enabled.
