### ISSUE TITLE
Add "Record-Armed Tracks" Track Target

### ISSUE THREAD

**Issue by arthurmcarthur1** [helgoboss/realearn#463]
It would be very useful to target only the tracks that are record armed

**Comment by helgoboss** [comment]
You mean a target option "Track must be armed", similar to "Track must be selected"?

If so, I'm planning to tackle this via a more generic feature: Conditional activation based on the value of the target of another mapping. Otherwise, this would be a never ending story (users asking for "Track must be unmuted", "Track must be soloed", etc.). With conditional activation based on the state of another target, this could all be handled, even things like "Volume must be greater than -6 dB". There's an issue for that already.

**Comment by arthurmcarthur1** [comment]
Yes, that would be perfect!

**Comment by helgoboss** [comment]
Ok, then closing in favor of #392
