### ISSUE TITLE
Add “Global: Last touched” options

### ISSUE THREAD

**Issue by Rodilab** [helgoboss/realearn#493]
The "Global: Last touched" is really very interesting. However I don't use it, because it is too "global"...
For example, if I touched a track, it will assign the fader to a "Select/Unselect track" toggle.

It could be interesting to choose the type of control we are interested in.
For example "Last touched pan" or "Last touched FX param". 
Or better, to be able to choose several : "Last touched send, pan, width or volume".

Thanks for reading

**Comment by m-malandro** [comment]
I agree with this request. As is, it is too unwieldy to use "Global: Last touched" to write automation. 

I think that you should be able to write automation like this:
-Have "Global: Last touched" assigned to an OSC fader
-Touch the fx parameter you want to automate
-Turn on an automation mode (e.g., "touch")
-Hit play, and use the OSC fader to write the automation.

This doesn't work because when you engage an automation mode (like "touch"), that becomes the "last touched" parameter. Currently, to get around this, you have to engage touch automation, then touch the fx parameter with the mouse (which creates an automation point, whether you want one or not), then hit play and start writing the automation.

**Comment by tompad2** [comment]
A friend of mine is running Cubase with an Audient soundcard(external usb). One nice thing with that is that you can control values of faders, textfield etc just by hoovering mouse over and turn a scrollwheel on the soundcard. I dont know if that 
works with Reaper but it would be REALLY nice to have that function with ReaLearn, wouldn't it? ;-)

**Comment by helgoboss** [comment]
> A friend of mine is running Cubase with an Audient soundcard(external usb). One nice thing with that is that you can control values of faders, textfield etc just by hoovering mouse over and turn a scrollwheel on the soundcard. I dont know if that works with Reaper but it would be REALLY nice to have that function with ReaLearn, wouldn't it? ;-)

See #686.

**Comment by helgoboss** [comment]
This gets more important to me now because of upcoming "Pot" preset navigation, where I want to use one display for displaying the last-touched value. It's also easier now because we have egui.

At this occasion, make it pick up more targets, also the new ones.

**Comment by PucksEvilTwin** [comment]
> I agree with this request. As is, it is too unwieldy to use "Global: Last touched" to write automation.
> 
> I think that you should be able to write automation like this: -Have "Global: Last touched" assigned to an OSC fader -Touch the fx parameter you want to automate -Turn on an automation mode (e.g., "touch") -Hit play, and use the OSC fader to write the automation.
> 
> This doesn't work because when you engage an automation mode (like "touch"), that becomes the "last touched" parameter. Currently, to get around this, you have to engage touch automation, then touch the fx parameter with the mouse (which creates an automation point, whether you want one or not), then hit play and start writing the automation.

I like this request, particularly what this person added on about last touched fx param automation.  But also as you pointed out the new NKS browsing.

**Comment by helgoboss** [comment]
Will be available in next pre-release.
