### ISSUE TITLE
FR: Internal Parameters avalaible as Source

### ISSUE THREAD

**Issue by X-Raym** [helgoboss/realearn#579]
Hi,

It would be nice to be able to use some ReaLearn Internal Parameters as source of mapping, so we can create mapping to some "dummy" envelopes rather than using MIDI, with the advantage of being in the 0-100 scale and being able to have named ranges.
This would prevent the use of using dummy JSFX, for which one file needed to be created, which makes project portability (for collab for eg) more complex. A ReaLearn Bult-in solution would be more handy.
Not sure how many of these parameters we would need, maybe 16?

Thx!

**Comment by helgoboss** [comment]
This will work in upcoming 1.13.0-pre.7. We have 100 parameters, one per compartment (the already existing ones). These parameters can be configured by right clicking the header panel and choosing "Compartment parameters" (name, optional discrete value count). If programmed via Lua, one can also assign labels to the discrete values.

I was a bit worried about infinite loops or stack overflow if someone accidentally routes e.g. "Parameter 1" source to "Parameter 1" target of the same instance. But turns out this is not a real issue because setting a parameter and reacting to the parameter change is decoupled (deferred). We get an infinite loop and the parameter will start to flicker, but one can simply stop it by choosing another source or target parameter or disabling the mapping. It's not going to freeze REAPER or tear down ReaLearn. So no counter measures are necessary.

**Comment by X-Raym** [comment]
@helgoboss many thanks for your work on this, can't wait to try !

**Comment by X-Raym** [comment]
@helgoboss Hi ! can you send me a .rpp or a screenshot about to use this feature ? I successfully renamed internal paramter but I dont know how to link them to anuthing else. Thx !

**Comment by helgoboss** [comment]
pre.7 is not published yet

**Comment by X-Raym** [comment]
@helgoboss oh ok. Off topic, but I sent you some GUI bugs screenshots on discord. Cheers !
