### ISSUE TITLE
"Paste mappings (replace all in group)" doesn't work with Default group

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/realearn#607]

**Comment by RattlesnakeLodge** [comment]
This may be related to an issue I'm experiencing in "pre-8".  I copy/paste a mapping from, for example, Group A to Group B.  

Group A is activated when bank selected:  Parameter 2, bank 3
Group B is activated when bank selected:  Parameter 2, bank 4

The mapping in Group A is then lost, as if it was a "move" action instead of copy/paste.  The pasted mapping in Group B cannot be activated, even when all conditions are met.  I suspect that mapping may have somehow retained Group A's activation conditions, and not inherited the intended conditions in Group B.

**Comment by helgoboss** [comment]
@RattlesnakeLodge Thanks for reporting! That's a pretty nasty bug! Fixing.

**Comment by helgoboss** [comment]
Opened new ticket #608 for that.
