### ISSUE TITLE
Realearn instances active in background project tabs

### ISSUE THREAD

**Issue by sclobster** [helgoboss/realearn#657]
Even with 'Run background projects' disabled, realearn is active in background project tabs.

When I move a knob on my midi controller, the connected Targets in all the project tabs change. When I switch between tabs, realearn instances in all the project tabs are sending out feedback.

I have tested this with Reaper 6.66 and ReaLearn 2.13.1.

**Comment by helgoboss** [comment]
Note to self:

I'm thinking about introducing a per-instance menu "Stay active when project in background" with the following options:

a. "Never"
b. "Only if background project is running"
c. "Always (as far as possible)"

That should cover every use case. Recently I wished there would be option a so I could hear audio from the other project tab but not control it anymore. Option b is how I thought it worked so far but doesn't really. Option c could be interesting for people who want to keep the current behavior (which is a bit inconsistent because I think it works when you choose a device as input or output but doesn't work if you choose FX input/output).
