### ISSUE TITLE
Virtual Button / Mode "Toggle Button" / Reverse Target possible?

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#734]
I have one virtual button, and I want to control two targets in the VST, but one in opposite direction.
ReaLearn offers "Reverse", but this only affects the feedback. For my use case, it would be good to have "reverse" also for the control direction.

**Comment by helgoboss** [comment]
This is possible already. "Reverse" works in control direction as well, not just feedback.

Please reopen if this is about some strange situation in which it doesn't work.

**Comment by vonglan** [comment]
I think the problem is that the button controlling that is "toggle-only".
So it always sends "1".
That can always invert the state of the VST button. But it can not force this to be in opposite directions.

**Comment by helgoboss** [comment]
Mmh, that shouldn't be an issue. Reverse should convert the 1 to a 0. I think there's something else at play here

**Comment by vonglan** [comment]
> Mmh, that shouldn't be an issue. 

I think it makes sense. If both VST buttons have initial state 1.
Then the "toggly-only" signal (controller mapping), maybe in conjunction with the "Toggle button" mode in the Main Mappping, will change both to 0, no matter if "reverse" is set in one of the mappings or not.
Because (I assume) "toggle-only" always switches the target to the other state.

**Comment by helgoboss** [comment]
"Toggle-only" source is intended for buttons that toggle natively (on the hardware already). Such buttons emit ON when pressed the first time and OFF when pressing the second time. They emit nothing on release. The fact that the hardware itself decides about the state (OFF or ON) is suboptimal for the user.

To be able to still use such buttons with ReaLearn without having to obey the hardware state, one chooses character "Toggle-only button". Then the source will always emit ON on press and nothing in release. It's better because then this button can be used as a trigger button and for real relative toggling depending on REAPER target state.

So this button character can not only be used for toggling (toggle mode), also for triggering (normal mode).

Your problem is simply related to "Toggle mode". Toggle mode always puts the target in the opposite state. If both VST parameters are OFF in the beginning, that means they will always be synchronized.

The solution is to initially put them to opposite states.

**Comment by vonglan** [comment]
> Your problem is simply related to "Toggle mode". Toggle mode always puts the target in the opposite state. If both VST parameters are OFF in the beginning, that means they will always be synchronized.

Yes.

> The solution is to initially put them to opposite states.

Yes, that would be possible, but I don't like that it requires manual activity to start. I rather don't support those two VST parameters with my preset. They are rarely used parameters anyway. (With the SY parameter set, I never support all parameters anyway.)

**Comment by helgoboss** [comment]
You can force-set a parameter to a specific value by using source "ReaLearn instance started" (or something like that).

**Comment by vonglan** [comment]
ah! Sounds good.
