### ISSUE TITLE
"Filter Source" becomes frozen after I go into a mapping

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#735]
When I use "Filter source", it is "active", and the button changes to "Stop".
When I edit that mapping (just open the window), and close the edit window again. The button label "Stop" has been automatically been replaced with "Filter source", but the "X" next to it is still black (not greyed out), and still only the one mappping is shown.

When I turn a different control now, only the previously filtered mapping is shown, and the filtered mapping is not updated.

Is it intended like this?
I had expected that the normal filtering mode continuous after closing the mapping window (or that the filtering mode is completely deactivated and all mappings of the selected group are shown again).

**Comment by helgoboss** [comment]
It's intended. Source filtering will automatically be stopped on certain events. ReaLearn just assumes the user forgot to turn it off. Not doing it could be very confusing for users who really forgot turning it off. Because as long as filtering is enabled, control will not work.

However, the source filter will not be cleared. That would be too much "Bevormuttern" by ReaLearn.

**Comment by vonglan** [comment]
very low prio, but what about

> or that the filtering mode is completely deactivated and all mappings of the selected group are shown again

**Comment by helgoboss** [comment]
As I said, too much "Bevormuttern". I wouldn't want that as a user. As a user, I set the filter for a reason. Then it's also my responsibility to unset it.
