### ISSUE TITLE
14 bit MIDI CC min value improperly handled

### ISSUE THREAD

**Issue by cjunekim** [helgoboss/realearn#76]
![realearn 14bit 2](https://user-images.githubusercontent.com/9114235/103144996-3ffa1880-4776-11eb-9e4d-af26bf4ff741.gif)

When I turn on 14-bit values option, realearn is supposed to handle 14 bit MIDI cc messages properly. However, it has some bug.

In this setting, the midi controller is sending a 14-bit cc message as MIDI cc 7 and 39 (volume MSB and LSB).

As you can see from the attached screen recording, the controller's MIDI cc values vary from 1 1(in the order of MSB, LSB), 2 2, 3 3, 4 4 and then back to 3 3, 2 2 ,1 1, 0 0. However when it gets down to 0 0, realearn interprets this as 0.78, instead of 0. So when as the midi controller goes up, you can see the realearn's Value jumps up and down. It goes like 0.78, 0.01 and then 0.79. Instead, it should monotonically increase.

**Comment by helgoboss** [comment]
What controller hardware is this? ReaLearn expects the MSB to be sent first (just like REAPER does it when drawing 14-bit CC messages in the MIDI editor) but yours seems to send the LSB first. So at the point when you are back to zero, the situation for ReaLearn is: MSB = 1, LSB = 0 (**not** MSB = 0, LSB = 0). Translated to the 14-bit value range this corresponds to 128 (out of 16383) - because 14-bit value = MSB * 128 + LSB. Translated to the volume value range this is probably the 0.78 you are seeing.

But not just the order of MSB/LSB seems strange here. It's also the values themselves. The purpose of 14-bit CC is to increase the resolution. The way I see it, increasing the MSB and the LSB together (0/0, 1/1, 2/2, ...) doesn't make sense at all. Either you take advantage of the full resolution: 0/0, 0/1, 0/2, 0/3, ..., 0/127, 1/0, 1/1, 1/2, ..., 127/127 (MSB/LSB). Or in case you want to simulate normal 7-bit MIDI, you just let the MSB run and leave the LSB at zero (0/0, 1/0, 2/0, ..., 127/0).

Here's the test case for the 14-bit CC scanning:
https://github.com/helgoboss/helgoboss-midi/blob/9a2ab82f6538da4ea1021d82eaed8efdebaf68a8/src/control_change_14_bit_message_scanner.rs#L144

**Comment by cjunekim** [comment]
Thanks for the quick response. This is interesting.

First of all, the order of LSB/MSB seems to be confusing. https://community.vcvrack.com/t/14-bit-midi-in-1-0/1779/57 Especially, look at delexander's quote and Vortico's reply.

I was actually using MIDI CC Mapper X https://forum.cockos.com/showthread.php?t=172630 The reason I was using this was to use a custom CC translation curve. The two are a fantastic pair. 

I tried it with 1 byte CC messages and the resolution was just too bad, for example with reacomp's ratio. I turned on High-Res mode in MIDI CC Mapper X. It seemed to work with some translation maps(for example Circle), but it failed to work with linear 1 to 1 mapping, in ReaLearn.

I looked into the source code of MIDI CC Mapper X and found:

>     controlHasOperationalHighResOutput(blk_control) ? (
>          // Output high res
>          midiCCHresF012I(out_val_01);    
>          // Send lsb first then msb
>          midiSend(evt.mpos, out_status, ccLsbCounterpart(out_cc_num),  g_hres_l);
>          midiSend(evt.mpos, out_status, out_cc_num,                    g_hres_h);

The author was quite explicit about this order of LSB and then MSB. As soon as I reversed the order, it seemed to work well with ReaLearn.

**Comment by helgoboss** [comment]
I agree with Vortico's reply: The part of the spec that says "When an MSB is received, the receiver should set its concept of the LSB to zero." makes it pretty clear that the MSB should come first. Maybe you can report this to the author of MIDI CC Mapper X (cool JSFX, didn't know that)? If I remember correctly, 14-bit (N)RPN requires the value LSB to be sent first and then the value MSB - but (N)RPN is not the same as 14-bit CC.

**Comment by BenTalagan** [comment]
Hi. I'm the author of MIDI CC Mapper X :). Thank you @cjunekim for reporting! By chance I'm currently already reworking that part in the plugin to make things work better with 14 bit MIDI CCs. We had a long discussion recently on the forum about 14-bit MIDI CCs and it appears that the MIDI specification itself have some drawbacks. Anyone interested can dig the thread about MIDI CC Mapper X on the forum, starting from this post : https://forum.cockos.com/showthread.php?p=2374090#post=2374090. Until it's ready, I'm really sorry for the inconvenience!

**Comment by helgoboss** [comment]
Hi @BenTalagan. Nice you chime in! Yes, it appears the MIDI spec itself is a bit unclear here. Back then I was looking at the way REAPER does it and I think JUCE handles it in the same way (MSB first). Thanks for adjusting your JSFX.

**Comment by BenTalagan** [comment]
Hi @cjunekim, @helgoboss , a quick message here to get you informed that I've released today a new version of MIDI CC Mapper X (4.3) which should address the MSB/LSB issue for High Res MIDI CC Controls we talked about in this thread ! Very, very, sorry for the long wait, as it took almost two years to me to release this new version.

**Comment by helgoboss** [comment]
Cool, thanks for the info!

**Comment by helgoboss** [comment]
Cool, thanks for the info!
