### ISSUE TITLE
Mapping :: Target :: Parameter List empty when target FX looses focus

### ISSUE THREAD

**Issue by TheSoundOfOneHandClapping** [helgoboss/realearn#778]
Hi
A problem popped up in the target section of the mapping editor: When you select

"Type: FX Parameter: Set value"
"FX: focused" and
"Parameter: particular",

the parameter drop down list is only populated as long as another Plugin has focus. As soon as you click the ReaLearn GUI to select a parameter, the list gets emptied and "<Requires FX>" is displayed. This obviously makes selecting a target this way impossible.

this is probably related to the latest change: "#770 Fixed FX still being considered as focused when focus is changed from the FX window to the main area."

Problem exists since ReaLearn 2.14.0-pre.11
MacOS Mojave 10.14.6
Reaper V6.70

**Comment by helgoboss** [comment]
Good catch! Well actually, the problem is not that it's impossible to select a target this way. The problem is that the GUI leads users to think it *should* be possible and make sense. In fact, it doesn't make sense at all!

The GUI should prevent users from selecting a parameter from a list when FX is set to "Focused"! Therefore, my solution will be to display a hint instead of "Requires FX", analogously how it's done if one chooses FX "Particular" and Track "By Name" (for example):

> Parameter: "Use 'Particular' only if FX is particular as well!"

The reason why it doesn't make sense is that FX "Focused" can be *any* FX and it can change at all times. It's not guaranteed that all FXs you ever focus have the same list of parameters, it's even highly unlikely. Presenting a dropdown list would make users think that this target only becomes active if exactly this kind of FX is focused with this particular list of parameters ... but that's not the case. ReaLearn doesn't care. This is why we have the "Auto-load" feature.

**Comment by TheSoundOfOneHandClapping** [comment]
this is confusing, probably I don't understand ReaLearn nowhere as good as I thought:

I always used this drop-down list to select the parameter when building mappings and it worked just fine  - it displayed the *real names* of the parameters of the last focused FX and not just "Main p1: Param 1", "Main p2: Param 2", etc

- why is this drop down list still there if it never gets populated with parameter names under any circumstances?
- How can you select a target manually (by human readable names) now?

and yes, of course I use the "Auto-load" feature to activate a mappings according to the focused FX - but that's in "live" mode, not in "build mappings" mode-

any insight is very appreciated, thank you

**Comment by helgoboss** [comment]
> * why is this drop down list still there if it never gets populated with parameter names under any circumstances?

It does get populated. But only if the FX is stable (e.g. "Particular" or "This"). Then you can safely select a parameter. This is also the default if you learn stuff.

> * How can you select a target manually (by human readable names) now?

By using FX "Particular" or "This".

> and yes, of course I use the "Auto-load" feature to activate a mappings according to the focused FX - but that's in "live" mode, not in "build mappings" mode-

Mmh, I understand. I always thought that most people use "Learn target" or "Learn Many" to build/modify their auto-load FX mapping presets, just because it's so convenient. And the more technical folks use "Named" or "At position". But some like you seem to prefer a dropdown, I was not thinking of that.

Maybe I should make this possible again with Focused. Damn, it's an annoying problem to solve. Because in reality, the FX is not focused anymore. But I have to present it as if it would still be focused ... isn't that confusing to users as well? It was just working because of the #770 bug before now.

**Comment by helgoboss** [comment]
If you have a good idea, let me know. I was hoping to publish 2.14.0 tomorrow but this one will probably delay it.

**Comment by helgoboss** [comment]
Okay, I think I will reactivate the dropdown menu even FX is set to Focused or other "unstable" options. Then I introduce a special handling for Focused so it always shows parameters for the FX instance that has last been focused.

This brings back the problem that users can easily be misled into thinking that their parameter choice is somehow bound to this last focused FX type (which it is not) ... so I guess I will display a warning in the help panel at the bottom whenever someone selects a parameter while FX is set to Focused.

**Comment by TheSoundOfOneHandClapping** [comment]
thank you for your elaborate answer and your time.

> By using FX "Particular" or "This".

indeed, with track, fx & Parameter all set to particular the drop down shows the human readable parameter names. But when saved, ReaLearn displays the "Some of the mappings have references to this particular project." message - when you click convert and later want to edit the mapping again, you're back to square one and must change 3 fields to "particular" to populate the dropdown again.

> Okay, I think I will reactivate the dropdown menu even FX is set to Focused or other "unstable" options. Then I introduce a special handling for Focused so it always shows parameters for the FX instance that has last been focused.

I would have suggested exactly this, to simply ignore when ReaLearn gets focused. I was never confused or misled by what it was, but I guess a warning message won't hurt.

thank you, this is much appreciated!

**Comment by TheSoundOfOneHandClapping** [comment]
That's a neat and cristal-clear solution you came up with in the latest release,
thank you so much for bringing this functionality back!
