### ISSUE TITLE
ReaLearn Controller Compartment in Monitor FX forgets parameter configuration when loading project

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#779]
I have a project which has ReaLearn in the Monitor FX chain.
Everytime I load it, the parameter configuration (especially: name and value count) is forgotten. (So bank selection does not work anymore.)
When I reload the preset, it's back.
When I save that as the new (correct) state of the project, and restart the project - it's forgotten again.

Ah, I guess Monitor FX are not part of the project.

#482 might be the topic, but that is solved.
Maybe not for the compartment parameter configuration?
(Controller compartment)

**Comment by vonglan** [comment]
Moved it into a track FX chain.
Same Problem.

**Comment by helgoboss** [comment]
Thanks. Wow, how is it possible that this problem remained undetected for so long! I just tested with 2.13.1 and even there we have it.

**Comment by helgoboss** [comment]
Now that I think about it, it makes sense. I never use parameters in the controller compartment. You might actually be the only one who does ;)

**Comment by rcaia** [comment]
I was just going to report this issue... I have been using controller parameters in a setup for my Launch Control XL in order to provide controller side flexible feedback options which would otherwise need to be in every main compartment preset.  It was working great except on project reload I kept loosing the parameter customizations.  The parameters ARE saved with the controller preset... just not loaded on startup... reloading the controller preset manually brings them back.

**Comment by helgoboss** [comment]
Fixing soon

**Comment by rcaia** [comment]
It's FIXED... Thanks much for getting to this so quickly.
