### ISSUE TITLE
FR: Instance FX parameter

### ISSUE THREAD

**Issue by tycho2112** [helgoboss/realearn#806]
It would be helpful to have an "Instance FX parameter" in order to "pin" last touched parameter to a specific fx parameter. For instance I have a controller mapped to "global: last touched" and I edit the threshold for a compressor. now that parameter is mapped to the "global: last touched" controller. I would be able to hit a modifier key that "pins" that mapping until the modifier is released so that I can go make other edits without loosing this temporary mapping.

**Comment by helgoboss** [comment]
The next pre-release will contain a new target "ReaLearn: Modify mapping" that allows you to pick a particular mapping and modify it. At the moment, 2 kinds of modifications are possible:

a) Learn target
b) Set target to last touched

I think your use case can then be implemented. But let's first assume a more simple use case: You have two knobs K1 and K2, where K1 should always control the last touched parameter and K2 always the last-pinned parameter.

I think in your current setup, you already have a mapping for K1, let's call it "Last touched". Now:

1. Add one additional mapping named "Pinned", with K2 as source. (For now, the target of that mapping is not relevant since it's going to change to whatever you will pin.)
2. Create one mapping named "Pin" with that new target "ReaLearn: Modify mapping" and option (b). Pick "Pinned" as the mapping that should be modified. Source: The modifier button that you were mentioning in the description.

Now, whenever you press the modifier button, it will pin the last touched target and you will be able to control it via K2.

In the use case that you described, you have one knob K1 only and you want it to control "Pinned" if the modifier button is pressed and "Last touched" if it's not pressed. This can be achieved using modifier-based conditional activation. So you need to add a mapping named "Switch" with the source being the modifier button (the same as the one that pins) and the target being a modifier parameter of ReaLearn. Then you set the activation conditions of mappings "Last touched" and "Pinned" to make sure that only one of them is active at a time.

Sounds more complicated than it is, I guess. It's just a combination of a new feature (the modify mapping target) and an old feature (conditional activation).

**Comment by helgoboss** [comment]
I think this solution is more general than having an "Instance FX parameter" because it works with all kinds of learnable targets, not just FX parameters. I hope to publish the pre-release tomorrow. Please let me know if this works for you and reopen the issue if it doesn't.

**Comment by tycho2112** [comment]
This is great thanks! Will give this a shot when I get home next week

**Comment by tycho2112** [comment]
tried this and doesn't seem to be working. When I hit the "Pin" button I
get "Created target hit instruction [invocation = 94, target = 1, control
value = 0] (normal control)" but nothing happens when turning the "Pinned"
knob.

**Comment by helgoboss** [comment]
Maybe you didn't choose which targets are included. There should be some possibility in the UI to pick the target types that will be taken into consideration. I think it was a button with 3 dots, can't recall now, AFK.

Also take a look at the other possible mapping modification "Learn target". This works more the way we discussed it in our last email conversation. The scenario you described there should now be possible as well.

**Comment by tycho2112** [comment]
ah yes that worked! I didn't even know about the included targets menu,
that's super helpful as I only ever want fx parameters included for "last
touched" anyways. pinning works perfectly, thank you for this!
