### ISSUE TITLE
Cycling between VSTs, mappings, and colors using MIDI Fighter Twister

### ISSUE THREAD

**Issue by stereokai** [helgoboss/realearn#833]
Hallo @helgoboss,

Hard to believe 2 years have passed by! Exactly 2 years ago I discovered ReaLearn and discussed some ideas with you, which culminated in the [MIDI Fighter Twister Color Designer](https://www.stereokai.com/midi-fighter-twister-color-designer) - was such a cool little project! – do you still support it?

I now have some time on my hands to finish what I had started back then. ReLearn has since grown tremendously and I don't know exactly where to begin. I'm sure you are as busy as ever, but if you could simply say what is supported and what isn't, and maybe point me to the right places in the manual, I'll be forever grateful.

Using MIDI Fighter Twister, here's what I'd like to get out of ReLearn, my endgame:

1. My project has a few tracks, each with 1 VST active. I'd like each VST to have its mapping.
2. Ability to cycle between these VST mappings by pressing a button (back and forth with 2 buttons - even nicer)
3. Ability to press an encoder-button to activate or disable a secondary mapping (both momentarily and latching-ly). Simultaneously this encoder-button could also be bound to a toggle control inside the VST - and needs to perform both actions at the same time.
4. Each VST mapping activates a different color scheme on the Midi Fighter Twister - and it should match the state of the VST at the moment of activation (for example if an on/off control (in the VST) or a secondary mapping is activated, it should be reflected in the colors at the moment the main mapping is activated). When a secondary mapping is *de*activated - I'd like the LEDs which were changed by it to revert to the previous active mapping' colors.

Bonus (maybe these could or should be achieved in combination with Reaper or SWS actions):

5. Twisting an encoder cycles through an FX chain of a specific track and will activate one FX at a time. Will be lovely if this mapping was reusable or shared between the different VST mappings.
6. Bring up/focus the VST when its mapping is active
7. Pressing a button to cycle the mapping brings the VST into focus
8. The whole setup should work in any project, if any mapped VST exists (assuming there is just one instance of it in a project), it all should work as expected

The 2 things I do remember are that I should use relative encoders and controller mappings instead of direct mappings 😁

P.S. I am completely blown away by the immense progress you have made with ReaLearn... The amount of features is absolutely staggering. Complements 😉

**Comment by helgoboss** [comment]
Looks like all of that can be done. But the devil is in the detail. Best you just give it a try. Start watching the ReaLearn tutorial videos.

**Comment by stereokai** [comment]
@helgoboss, thanks very much for your response. I'm sure you're as busy as ever, but any chance you could give me some pointers? ReaLearn has come such a long way since I last worked with it, which was around the time I built that color tool, that I'm frankly a little intimidated 😅

Also, are you still supporting that YAML syntax for sending the MIDI code back to the controller, as we used for the MFT color tool?

**Comment by helgoboss** [comment]
> 1. My project has a few tracks, each with 1 VST active. I'd like each VST to have its mapping.

If each VST should have its own set of mappings, it makes sense to save each set of mappings as "Main preset" and have one instance of ReaLearn that has "Auto-load" enabled (let's call that instance `auto`). "Auto-load" is a feature to automatically load the mappings for the VST that's currently active. Where "active" can mean virtually anything, e.g. the currently focused VST or a VST that has been currently "pinned" within ReaLearn ... no matter what, this is managed in ReaLearn via "Instance FX" (see user guide). I think in your case, it would make sense to make your "Instance FX" always refer to the first FX of the currently selected track ...

> 2. Ability to cycle between these VST mappings by pressing a button (back and forth with 2 buttons - even nicer)

... so that cycling between the VST mappings gets simply a matter of selecting tracks. You can do that by adding a second ReaLearn instance (let's call it `permanent`) by using the target "Project: Browse tracks" and map this (via 2 mappings) to 2 buttons using mode "Incremental button", one with "reverse" to go back and forth.

> 3. Ability to press an encoder-button to activate or disable a secondary mapping (both momentarily and latching-ly). Simultaneously this encoder-button could also be bound to a toggle control inside the VST - and needs to perform both actions at the same time.

This would probably be handled *within* the VST-specific main preset. Using modifier-based conditional activation (Active = "When modifier on/off"). Whether momentarily or latchingly is then just a matter of how you map your button to the modifier parameter (either mode "Normal" or mode "Toggle button").

Additionally binding the encoder button to a control inside the VST is just a matter of adding another mapping in your VST-specific main preset.

> 4. Each VST mapping activates a different color scheme on the Midi Fighter Twister - and it should match the state of the VST at the moment of activation (for example if an on/off control (in the VST) or a secondary mapping is activated, it should be reflected in the colors at the moment the main mapping is activated). When a secondary mapping is _de_activated - I'd like the LEDs which were changed by it to revert to the previous active mapping' colors.

In your case, colors are dynamic. They depend on the target state (e.g. a VST on/off control). That means that your color tool / my YAML mechanism can't be used because it's static in nature. But you can just use "Source min/max" in each VST-scecific mapping. This influences the LED color for off/on. Changing the "Instance FX" (point 2) and the state for "conditional activation" (point 3) should automatically take care of making all LEDs reflect the current state.

> 
> Bonus (maybe these could or should be achieved in combination with Reaper or SWS actions):
> 
> 5. Twisting an encoder cycles through an FX chain of a specific track and will activate one FX at a time. Will be lovely if this mapping was reusable or shared between the different VST mappings.

This is done using target "Track: Browse FXs", where "activating" means "bringing the FX into focus".

> 6. Bring up/focus the VST when its mapping is active

If you want this workflow (point 5 and 6 sounds like it), you are probably better off, setting the instance FX of your `auto` ReaLearn instance to "<Focused>". Then it will always refer to the currently focused VST.

> 7. Pressing a button to cycle the mapping brings the VST into focus

I don't understand this point.

> 8. The whole setup should work in any project, if any mapped VST exists (assuming there is just one instance of it in a project), it all should work as expected

You make it available in all projects by putting the 2 instances on the monitoring FX chain. Attention: Build your setup FIRST as part of a project, because REAPER is not very reliable when it comes to undo/backup/saving of monitoring FX chain.

> 
> The 2 things I do remember are that I should use relative encoders and controller mappings instead of direct mappings 😁

Yes, "Relative" mode for encoders, always!

Controller mappings ... I would recommend it, but it's not a hard requirement. The reasons why you might want to do it are explained in the user guide.

> 
> P.S. I am completely blown away by the immense progress you have made with ReaLearn... The amount of features is absolutely staggering. Complements 😉

Thanks!

**Comment by stereokai** [comment]
> > 1. My project has a few tracks, each with 1 VST active. I'd like each VST to have its mapping.
> 
> If each VST should have its own set of mappings, it makes sense to save each set of mappings as "Main preset" and have one instance of ReaLearn that has "Auto-load" enabled (let's call that instance `auto`). "Auto-load" is a feature to automatically load the mappings for the VST that's currently active. Where "active" can mean virtually anything, e.g. the currently focused VST or a VST that has been currently "pinned" within ReaLearn ... no matter what, this is managed in ReaLearn via "Instance FX" (see user guide). I think in your case, it would make sense to make your "Instance FX" always refer to the first FX of the currently selected track ...
> 
This sounds great. Just one thing - I realized, I do actually have a couple of tracks with more than one VST, and the "main" VST of that track could be in the middle of the chain, i.e. not first and not last. How would you go about that?
> > 2. Ability to cycle between these VST mappings by pressing a button (back and forth with 2 buttons - even nicer)
> 
> ... so that cycling between the VST mappings gets simply a matter of selecting tracks. You can do that by adding a second ReaLearn instance (let's call it `permanent`) by using the target "Project: Browse tracks" and map this (via 2 mappings) to 2 buttons using mode "Incremental button", one with "reverse" to go back and forth.
> 
Very clear. Sounds great!
> > 3. Ability to press an encoder-button to activate or disable a secondary mapping (both momentarily and latching-ly). Simultaneously this encoder-button could also be bound to a toggle control inside the VST - and needs to perform both actions at the same time.
> 
> This would probably be handled _within_ the VST-specific main preset. Using modifier-based conditional activation (Active = "When modifier on/off"). Whether momentarily or latchingly is then just a matter of how you map your button to the modifier parameter (either mode "Normal" or mode "Toggle button").
> 
> Additionally binding the encoder button to a control inside the VST is just a matter of adding another mapping in your VST-specific main preset.
> 
Very clear! Fantastic!
> > 4. Each VST mapping activates a different color scheme on the Midi Fighter Twister - and it should match the state of the VST at the moment of activation (for example if an on/off control (in the VST) or a secondary mapping is activated, it should be reflected in the colors at the moment the main mapping is activated). When a secondary mapping is _de_activated - I'd like the LEDs which were changed by it to revert to the previous active mapping' colors.
> 
> In your case, colors are dynamic. They depend on the target state (e.g. a VST on/off control). That means that your color tool / my YAML mechanism can't be used because it's static in nature. But you can just use "Source min/max" in each VST-specific mapping. This influences the LED color for off/on. Changing the "Instance FX" (point 2) and the state for "conditional activation" (point 3) should automatically take care of making all LEDs reflect the current state.
> 
I'm not sure I fully understand how this part is supposed to work (assuming that the colors are set by the "instance fx mapping", using the YAML format. By "This influences the LED color for off/on", do you mean the LED color which is hardware-configured in the MFT? Or something else?
> > Bonus (maybe these could or should be achieved in combination with Reaper or SWS actions):
> > 
> > 5. Twisting an encoder cycles through an FX chain of a specific track and will activate one FX at a time. Will be lovely if this mapping was reusable or shared between the different VST mappings.
> 
> This is done using target "Track: Browse FXs", where "activating" means "bringing the FX into focus".
> 
Apologies for being unclear here. By "activating", I meant "turn on/off". Meaning, I'd like to turn an encoder, and it will cycle between the effects in a chain, turning only one VST on at a time. This is for a separate track than the ones mentioned in point 1. Meaning another context than the "instance FX".
> > 6. Bring up/focus the VST when its mapping is active
> 
> If you want this workflow (point 5 and 6 sounds like it), you are probably better off, setting the instance FX of your `auto` ReaLearn instance to `<Focused>`. Then it will always refer to the currently focused VST.
> 
Again apologies for being unclear. This does refer again to the main tracks from point 1. Using `<Focused>` sounds however like ReaLearn will respond to which VST is focused, while I was hoping to achieve the inverse behavior, ReaLearn should bring a VST into focus in case its mapping was activated (by point 2).
> > 7. Pressing a button to cycle the mapping brings the VST into focus
> 
> I don't understand this point.
> 
I hope I just explained that better above :)
> > 8. The whole setup should work in any project, if any mapped VST exists (assuming there is just one instance of it in a project), it all should work as expected
> 
> You make it available in all projects by putting the 2 instances on the monitoring FX chain. Attention: Build your setup FIRST as part of a project, because REAPER is not very reliable when it comes to undo/backup/saving of monitoring FX chain.
> 
Amazing! 
> > The 2 things I do remember are that I should use relative encoders and controller mappings instead of direct mappings 😁
> 
> Yes, "Relative" mode for encoders, always!
> 
> Controller mappings ... I would recommend it, but it's not a hard requirement. The reasons why you might want to do it are explained in the user guide.
> 
> > P.S. I am completely blown away by the immense progress you have made with ReaLearn... The amount of features is absolutely staggering. Complements 😉
> 
> Thanks!

Thank you!

**Comment by helgoboss** [comment]
> This sounds great. Just one thing - I realized, I do actually have a couple of tracks with more than one VST, and the "main" VST of that track could be in the middle of the FX chain, i.e. not first and not last. Apologies for the error. How would you go about that?

Depends on how you want it to work. You could for example use an internal ReaLearn parameter that memorizes which FX (the first, the second, ...) you currently want to work on. Then you would configure the instance FX with FX <Dynamic> and use a dynamic expression such as `p1`. This assumes that you chose the first main compartment parameter to represent the memorized position in the FX chain. You can make this more "prominent" by giving this parameter an appropriate name: Menu => Compartment parameters => Parameter 1 => Name "FX index". Oh yes, and you need to choose a value count (something like 100, it should be constant), otherwise `p1` will always be a floating point number between 0.0 and 1.0

> > In your case, colors are dynamic. They depend on the target state (e.g. a VST on/off control). That means that your color tool / my YAML mechanism can't be used because it's static in nature. But you can just use "Source min/max" in each VST-specific mapping. This influences the LED color for off/on. Changing the "Instance FX" (point 2) and the state for "conditional activation" (point 3) should automatically take care of making all LEDs reflect the current state.
> 
> I'm not sure I fully understand how this part is supposed to work (assuming that the colors are set by the "instance fx mapping", using the YAML format). By "This influences the LED color for off/on", do you mean the LED color which is hardware-configured in the MFT? Or something else?

The MFT LEDs work like the LEDs in lots of other controllers: You can control each one of them using a simple MIDI messages. And the value that you send influences the LED color. Works the same way on the Launchpad or other pad controllers. Which type of message you need to send depends on how you configured the button (encoder push) above the LED in the MFT utility. E.g. if you have configured "Switch MIDI Number 15", then you can control the LED with CC 15 messages. Sending a value of 0 will switch the LED off or to the default state, I don't remember. (The default state maybe being the one that you store in the hardware e.g. using the YAML).

So I recommend you to just play around with it and get a feeling of how it works. In your case, I would probably completely avoid using the YAML method. I don't know how those 2 interact, it could be contradicting at some point and you might run into order issues. At the end, it's 2 methods controlling one and the same resource - the LED.

> > > 5. Twisting an encoder cycles through an FX chain of a specific track and will activate one FX at a time. Will be lovely if this mapping was reusable or shared between the different VST mappings.
> > 
> > 
> > This is done using target "Track: Browse FXs", where "activating" means "bringing the FX into focus".
> 
> Apologies for being unclear here. By "activating", I meant "turn on/off". Meaning, I'd like to turn an encoder, and it will cycle between the effects in a chain, turning only one VST on at a time. It doesn't need to bring them into focus. This is for a separate track than the ones mentioned in point 1. Meaning another context than the "instance FX".

This is maybe possible by adding many mappings with target "FX: Enable/disable" (one for each FX position) in one mapping group. Source can be "None". Then create another mapping "Cycle" in another group with the encoder as source and target "ReaLearn: Browse group mappings", setting exclusivity to "Exclusive". Didn't try it though. "FX: Enable/disable" doesn't have any built-in exclusivity setting, so you need to take the "Browse group mappings" way.

> > > 6. Bring up/focus the VST when its mapping is active
> > 
> > 
> > If you want this workflow (point 5 and 6 sounds like it), you are probably better off, setting the instance FX of your `auto` ReaLearn instance to `<Focused>`. Then it will always refer to the currently focused VST.
> > > 7. Pressing a button to cycle the mapping brings the VST into focus
> > 
> > 
> > I don't understand this point.
> 
> Again apologies for being unclear. 6 & 7 basically mean the same. This does refer again to the main tracks from point 1. However, your suggestion to use `<Focused>` sounds like ReaLearn will respond to which VST is currently focused, while I was hoping to achieve the inverse behavior, ReaLearn should bring a VST into focus in case its mapping was activated (by point 2).

You could achieve the reverse by using the method I described in the first answer (dynamic expression) and map the encoder turn also to "FX: Open/close". But that wouldn't close the the other FX in the chain ... so I don't know how I would go about that. Your desired behavior is so special that it might be a good idea to write a ReaScript that's invoked on each encoder turn. It could take care of enabling/disabling and showing FX.

**Comment by stereokai** [comment]
> Depends on how you want it to work. You could for example use an internal ReaLearn parameter that memorizes which FX (the first, the second, ...) you currently want to work on. Then you would configure the instance FX with FX and use a dynamic expression such as p1. This assumes that you chose the first main compartment parameter to represent the memorized position in the FX chain. You can make this more "prominent" by giving this parameter an appropriate name: Menu => Compartment parameters => Parameter 1 => Name "FX index". Oh yes, and you need to choose a value count (something like 100, it should be constant), otherwise p1 will always be a floating point number between 0.0 and 1.0

Thank you so much. Does it mean I will have to add a separate ReaLearn instance for each VST I'd like to control? Otherwise, how do I ensure that the "auto-load" ReaLearn or the "permanent" ReaLearn (that you described above) know which compartment parameter to associate with each track?

> So I recommend you to just play around with it and get a feeling of how it works. In your case, I would probably completely avoid using the YAML method. I don't know how those 2 interact, it could be contradicting at some point and you might run into order issues. At the end, it's 2 methods controlling one and the same resource - the LED.

If I understand you correctly, it sounds like you're suggesting using MFT's hardware color configuration. But isn't the whole purpose of the YAML method (just like relative encoders) to decouple ReaLearn's features from the hardware? So won't there be a conflict with the mappings per VST we discussed earlier? What I mean is, on one VST mapping, an encoder-button might have a particular on/off behavior and colors, and on another VST mapping, the same encoder-button might have a different on/off behavior and colors. And what I hope to achieve is, the colors should always reflect the active mapping as well as the state of the VST control they represent. I apologize if this sounds convoluted, this conversation is really testing my English skills 😅

> This is maybe possible by adding many mappings with target "FX: Enable/disable" (one for each FX position) in one mapping group. Source can be "None". Then create another mapping "Cycle" in another group with the encoder as source and target "ReaLearn: Browse group mappings", setting exclusivity to "Exclusive". Didn't try it though. "FX: Enable/disable" doesn't have any built-in exclusivity setting, so you need to take the "Browse group mappings" way.

Ok. I'll definitely give it a try :) Question: I could make a ReaScript or Reaper Action that would turn off all FX in the chain. This would then be followed by the cycle mapping enabling the "next" or "prev" FX. Can something like that be combined with the cycle mapping in ReaLearn and does it make it easier to set up this FX cycling behavior?

> You could achieve the reverse by using the method I described in the first answer (dynamic expression) and map the encoder turn also to "FX: Open/close". But that wouldn't close the the other FX in the chain ... so I don't know how I would go about that. Your desired behavior is so special that it might be a good idea to write a ReaScript that's invoked on each encoder turn. It could take care of enabling/disabling and showing FX.

How do I hook ReaLearn to a ReaScript? I couldn't find any clear mention in the user guide. There are many Lua/EEL mentions but none of which I could draw a connection to this context by myself.

Thanks a million again!
