### ISSUE TITLE
Too many realearn instances causes Reaper to crash when opening FX gui

### ISSUE THREAD

**Issue by sclobster** [helgoboss/realearn#875]
If I have more than 550 instances of Realearn, as soon as I open the FX gui window for any track Reaper hangs and I have to force quit. It's the same if all instances in one project or spread across multiple project tabs.

I've attached two projects, one causes Reaper to freeze, the other doesn't:

[lots of realearns.zip](https://github.com/helgoboss/realearn/files/11961513/lots.of.realearns.zip)

**Comment by helgoboss** [comment]
I know why, could probably improve on that. However, before I do that: What's the practical use case for having so many instances? As a rule of thumb, one instance per device is usually enough?

**Comment by helgoboss** [comment]
Never mind, no matter if there's a practical use case or not ... I think this should be fixed.

## Background

It's a deadlock. ReaLearn often defers tasks *within the same thread* (the main thread) to be executed asynchronously and does this using channels/queues. In this case, the queue is full, so execution blocks. Too bad, because that means the main thread can't do anything anymore, not even process tasks in the queue - which would resolve the issue.

One solution would be to give up sending further tasks to the queue when it's full. But that also means, tasks that are probably important to achieve correct behavior are not going to be executed.

Another solution is to make this kind of queue unbounded. For main thread queues that's okay. That essentially makes your computer's memory the limit. I will try it that way.

**Comment by sclobster** [comment]
Brilliant thanks Helgoboss. I ran in to the problem with my live setup, I have multiple controllers and one song per project tab. When putting together a longer set I've managed to reach this number. I have no more than one instance per track per controller, but there are also a bunch of utility tracks I need to make everything work, and things duplicated across groups, somehow it's added up.

**Comment by helgoboss** [comment]
Will be fixed in 2.16.0-pre.2. Tried the fix with your project locally and it works now.
