### ISSUE TITLE
Midi Fighter set pan on selected track defaults to 0.8%R on center (in Reaper)

### ISSUE THREAD

**Issue by captainshern** [helgoboss/realearn#912]
Hello,

I am trying to use a Midi fighter to simply control the pan on a selected track in reaper.

Here are my settings:
![shot_240130_133711](https://github.com/helgoboss/realearn/assets/158210633/835aa3ba-425d-4f68-bcc4-bd8c56bcecf5)

When I move the knob on my Midifighter its center defaults to 0.8%R instead of the center pan. 
I wondered if there was a way to fix this so that it goes to the 'center value' of the pan when the knob is centered.

Here is a screenshot of my pan in reaper:

![shot_240130_133946](https://github.com/helgoboss/realearn/assets/158210633/14cd1541-2de8-44ff-bcf4-dba2a2cf3e89)

Cheers.
Steven

**Comment by helgoboss** [comment]
This is because you are using absolute control. This means 128 steps which is an even number, which means there can't be a real center (128 / 2 = 64 = slightly to the right ... and 63 = slightly to the left).

The best way to solve this is to configure the encoders to send relative messages, in the Twister editor. I always tell people to do so because leaving them in absolute mode is like not using the biggest advantage of endless encoders ;)

If you insist on absolute messages, you need to restrict source min/max so that you get an odd number. Or you write a small control transformation scripts that snaps to the center.

**Comment by captainshern** [comment]
Hey Helgoboss,

Thanks for the info, it helps. Although I checked the twister editor (MF utility) and they don't allow me to send relative message per encoder, maybe it's called differently?

This is what I have:

![shot_240130_142143](https://github.com/helgoboss/realearn/assets/158210633/2f866d4e-a032-4ea3-ac9e-666318314990)

**Comment by helgoboss** [comment]
https://github.com/helgoboss/realearn/blob/master/doc/controllers.adoc contains setup instructions.
